### ISSUE TITLE
审阅 EI-投票小游戏

### ISSUE THREAD

**Issue by pimgeek** [icpdao/ei-voting-game#4]
主要工作：

* 审阅 EI-投票小游戏，尝试理解它想表达的意思
* 把影响理解或影响体验的部分总结出来
* 以图文总结的方式，提交 Markdown 文档

**Comment by pimgeek** [comment]
申请开发 deadline：2021-04-06 size：0.5 @nancy919

**Comment by nancy919** [comment]
1

**Comment by nancy919** [comment]
1

**Comment by nancy919** [comment]
1
